In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('ionosphere_data.csv')

In [3]:
dataset.head()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
0,1,0,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,0,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,0,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,0,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,0,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g

In [4]:
dataset.tail()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
346,1,0,0.83508,0.08298,0.73739,-0.14706,0.84349,-0.05567,0.90441,-0.04622,...,-0.04202,0.83479,0.00123,1.00000,0.12815,0.86660,-0.10714,0.90546,-0.04307,g
347,1,0,0.95113,0.00419,0.95183,-0.02723,0.93438,-0.01920,0.94590,0.01606,...,0.01361,0.93522,0.04925,0.93159,0.08168,0.94066,-0.00035,0.91483,0.04712,g
348,1,0,0.94701,-0.00034,0.93207,-0.03227,0.95177,-0.03431,0.95584,0.02446,...,0.03193,0.92489,0.02542,0.92120,0.02242,0.92459,0.00442,0.92697,-0.00577,g
349,1,0,0.90608,-0.01657,0.98122,-0.01989,0.95691,-0.03646,0.85746,0.00110,...,-0.02099,0.89147,-0.07760,0.82983,-0.17238,0.96022,-0.03757,0.87403,-0.16243,g
350,1,0,0.84710,0.13533,0.73638,-0.06151,0.87873,0.08260,0.88928,-0.09139,...,-0.15114,0.81147,-0.04822,0.78207,-0.00703,0.75747,-0.06678,0.85764,-0.06151,g

In [5]:
dataset.describe()

,feature1,feature2,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,...,feature25,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34
count,351.000000,351.0,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,...,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000,351.000000
mean,0.891738,0.0,0.641342,0.044372,0.601068,0.115889,0.550095,0.119360,0.511848,0.181345,...,0.396135,-0.071187,0.541641,-0.069538,0.378445,-0.027907,0.352514,-0.003794,0.349364,0.014480
std,0.311155,0.0,0.497708,0.441435,0.519862,0.460810,0.492654,0.520750,0.507066,0.483851,...,0.578451,0.508495,0.516205,0.550025,0.575886,0.507974,0.571483,0.513574,0.522663,0.468337
min,0.000000,0.0,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,...,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000,-1.000000
25%,1.000000,0.0,0.472135,-0.064735,0.412660,-0.024795,0.211310,-0.054840,0.087110,-0.048075,...,0.000000,-0.332390,0.286435,-0.443165,0.000000,-0.236885,0.000000,-0.242595,0.000000,-0.165350
50%,1.000000,0.0,0.871110,0.016310,0.809200,0.022800,0.728730,0.014710,0.684210,0.018290,...,0.553890,-0.015050,0.708240,-0.017690,0.496640,0.000000,0.442770,0.000000,0.409560,0.000000
75%,1.000000,0.0,1.000000,0.194185,1.000000,0.334655,0.969240,0.445675,0.953240,0.534195,...,0.905240,0.156765,0.999945,0.153535,0.883465,0.154075,0.857620,0.200120,0.813765,0.171660
max,1.000000,0.0,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [6]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 351 entries, 0 to 350
Data columns (total 35 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   feature1   351 non-null    int64
 1   feature2   351 non-null    int64
 2   feature3   351 non-null    float64
 3   feature4   351 non-null    float64
 4   feature5   351 non-null    float64
 5   feature6   351 non-null    float64
 6   feature7   351 non-null    float64
 7   feature8   351 non-null    float64
 8   feature9   351 non-null    float64
 9   feature10  351 non-null    float64
 10  feature11  351 non-null    float64
 11  feature12  351 non-null    float64
 12  feature13  351 non-null    float64
 13  feature14  351 non-null    float64
 14  feature15  351 non-null    float64
 15  feature16  351 non-null    float64
 16  feature17  351 non-null    float64
 17  feature18  351 non-null    float64
 18  feature19  351 non-null    float64
 19  feature20  351 non-null    float64
 20  feature21  351 non-null    float64
 21  feature22  351 non-null    float64
 22  feature23  351 non-null    float64
 23  feature24  351 non-null    float64
 24  feature25  351 non-null    float64
 25  feature26  351 non-null    float64
 26  feature27  351 non-null    float64
 27  feature28  351 non-null    float64
 28  feature29  351 non-null    float64
 29  feature30  351 non-null    float64
 30  feature31  351 non-null    float64
 31  feature32  351 non-null    float64
 32  feature33  351 non-null    float64
 33  feature34  351 non-null    float64
 34  label      351 non-null    object
dtypes: float64(32), int64(2), object(1)
memory usage: 96.1+ KB

In [7]:
dataset.isnull().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [8]:
dataset.isna().sum()

feature1     0
feature2     0
feature3     0
feature4     0
feature5     0
feature6     0
feature7     0
feature8     0
feature9     0
feature10    0
feature11    0
feature12    0
feature13    0
feature14    0
feature15    0
feature16    0
feature17    0
feature18    0
feature19    0
feature20    0
feature21    0
feature22    0
feature23    0
feature24    0
feature25    0
feature26    0
feature27    0
feature28    0
feature29    0
feature30    0
feature31    0
feature32    0
feature33    0
feature34    0
label        0
dtype: int64

In [9]:
dataset.feature2

0      0
1      0
2      0
3      0
4      0
      ..
346    0
347    0
348    0
349    0
350    0
Name: feature2, Length: 351, dtype: int64

In [10]:
# feature2 has 0 values, it's useless for the data so will drop this
dataset.drop(columns='feature2', inplace=True)

In [11]:
dataset.head(20)

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
0,1,0.99539,-0.05889,0.85243,0.02306,0.83398,-0.37708,1.00000,0.03760,0.85243,...,-0.51171,0.41078,-0.46168,0.21266,-0.34090,0.42267,-0.54487,0.18641,-0.45300,g
1,1,1.00000,-0.18829,0.93035,-0.36156,-0.10868,-0.93597,1.00000,-0.04549,0.50874,...,-0.26569,-0.20468,-0.18401,-0.19040,-0.11593,-0.16626,-0.06288,-0.13738,-0.02447,b
2,1,1.00000,-0.03365,1.00000,0.00485,1.00000,-0.12062,0.88965,0.01198,0.73082,...,-0.40220,0.58984,-0.22145,0.43100,-0.17365,0.60436,-0.24180,0.56045,-0.38238,g
3,1,1.00000,-0.45161,1.00000,1.00000,0.71216,-1.00000,0.00000,0.00000,0.00000,...,0.90695,0.51613,1.00000,1.00000,-0.20099,0.25682,1.00000,-0.32382,1.00000,b
4,1,1.00000,-0.02401,0.94140,0.06531,0.92106,-0.23255,0.77152,-0.16399,0.52798,...,-0.65158,0.13290,-0.53206,0.02431,-0.62197,-0.05707,-0.59573,-0.04608,-0.65697,g
5,1,0.02337,-0.00592,-0.09924,-0.11949,-0.00763,-0.11824,0.14706,0.06637,0.03786,...,-0.01535,-0.03240,0.09223,-0.07859,0.00732,0.00000,0.00000,-0.00039,0.12011,b
6,1,0.97588,-0.10602,0.94601,-0.20800,0.92806,-0.28350,0.85996,-0.27342,0.79766,...,-0.81634,0.13659,-0.82510,0.04606,-0.82395,-0.04262,-0.81318,-0.13832,-0.80975,g
7,0,0.00000,0.00000,0.00000,0.00000,1.00000,-1.00000,0.00000,0.00000,-1.00000,...,1.00000,1.00000,1.00000,0.00000,0.00000,1.00000,1.00000,0.00000,0.00000,b
8,1,0.96355,-0.07198,1.00000,-0.14333,1.00000,-0.21313,1.00000,-0.36174,0.92570,...,-0.65440,0.57577,-0.69712,0.25435,-0.63919,0.45114,-0.72779,0.38895,-0.73420,g
9,1,-0.01864,-0.08459,0.00000,0.00000,0.00000,0.00000,0.11470,-0.26810,-0.45663,...,-0.01326,0.20645,-0.02294,0.00000,0.00000,0.16595,0.24086,-0.08208,0.38065,b
10,1,1.00000,0.06655,1.00000,-0.18388,1.00000,-0.27320,1.00000,-0.43107,1.00000,...,-0.89128,0.47211,-0.86500,0.40303,-0.83675,0.30996,-0.89093,0.22995,-0.89158,g
11,1,1.00000,-0.54210,1.00000,-1.00000,1.00000,-1.00000,1.00000,0.36217,1.00000,...,-0.40888,1.00000,-0.62745,1.00000,-1.00000,1.00000,-1.00000,1.00000,-1.00000,b
12,1,1.00000,-0.16316,1.00000,-0.10169,0.99999,-0.15197,1.00000,-0.19277,0.94055,...,-0.47137,0.76224,-0.58370,0.65723,-0.68794,0.68714,-0.64537,0.64727,-0.67226,g
13,1,1.00000,-0.86701,1.00000,0.22280,0.85492,-0.39896,1.00000,-0.12090,1.00000,...,-0.17012,1.00000,0.35924,1.00000,-0.66494,1.00000,0.88428,1.00000,-0.18826,b
14,1,1.00000,0.07380,1.00000,0.03420,1.00000,-0.05563,1.00000,0.08764,1.00000,...,0.20033,1.00000,0.36743,0.95603,0.48641,1.00000,0.32492,1.00000,0.46712,g
15,1,0.50932,-0.93996,1.00000,0.26708,-0.03520,-1.00000,1.00000,-1.00000,0.43685,...,0.92236,0.39752,0.26501,0.00000,0.00000,1.00000,0.23188,0.00000,0.00000,b
16,1,0.99645,0.06468,1.00000,-0.01236,0.97811,0.02498,0.96112,0.02312,0.99274,...,0.13412,0.79476,0.13638,0.79110,0.15379,0.77122,0.15930,0.70941,0.12015,g
17,0,0.00000,0.00000,-1.00000,-1.00000,1.00000,1.00000,-1.00000,1.00000,-1.00000,...,1.00000,1.00000,-1.00000,-1.00000,1.00000,-1.00000,-1.00000,1.00000,-1.00000,b
18,1,0.67065,0.02528,0.66626,0.05031,0.57197,0.18761,0.08776,0.34081,0.63621,...,0.23724,0.46167,0.24618,0.43433,0.25306,0.40663,0.25792,1.00000,0.33036,g
19,0,1.00000,-1.00000,0.00000,0.00000,0.00000,0.00000,1.00000,1.00000,1.00000,...,1.00000,1.00000,1.00000,1.00000,-1.00000,1.00000,1.00000,1.00000,1.00000,b

In [12]:
dataset.label.value_counts()

g    225
b    126
Name: label, dtype: int64

In [13]:
# so here we will encode label column, b=1 and g=0
replace_values = {'label':{'g':0, 'b':1}}

In [14]:
dataset = dataset.replace(replace_values)

In [15]:
dataset = dataset.sample(frac=1)

In [16]:
dataset

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34,label
104,1,0.28409,-0.31818,0.00000,0.00000,0.68182,-1.00000,0.30682,0.95833,0.64394,...,0.17803,1.00000,-0.23864,0.06061,-0.48485,0.16288,-0.70076,0.00000,0.00000,1
128,1,0.00000,0.00000,-0.33672,0.85388,0.00000,0.00000,0.68869,-1.00000,0.97078,...,0.00000,1.00000,-1.00000,0.00000,0.00000,0.04447,0.61881,0.00000,0.00000,1
212,1,-1.00000,-0.59677,0.00000,0.00000,-1.00000,0.64516,-0.87097,1.00000,0.00000,...,0.23387,1.00000,0.51613,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,1
271,1,0.47938,-0.12371,0.42784,-0.12371,0.70103,-0.39175,0.73196,0.07216,0.26289,...,0.19588,0.53396,-0.12447,0.15464,-0.26289,0.47423,0.04124,0.45361,-0.51546,0
229,1,0.73523,-0.38293,0.80151,0.10278,0.78826,0.15266,0.55580,0.05252,1.00000,...,0.57549,0.44174,0.48200,0.12473,1.00000,0.35070,0.49721,0.30588,0.49831,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
318,1,0.74790,0.00840,0.83312,0.01659,0.82638,0.02469,0.86555,0.01681,0.60504,...,0.08403,0.63728,0.08296,0.61345,0.01681,0.58187,0.08757,0.55330,0.08891,0
202,1,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000,-0.85000,-1.00000,0.00000,...,1.00000,-1.00000,-0.20000,1.00000,-1.00000,0.00000,1.00000,0.00000,0.00000,1
299,1,0.83479,0.28993,0.69256,0.47702,0.49234,0.68381,0.21991,0.86761,-0.08096,...,-0.52954,-0.16950,-0.60863,0.08425,-0.61488,0.25164,-0.48468,0.40591,-0.35339,0
338,1,0.32789,0.11042,0.15970,0.29308,0.14020,0.74485,-0.25131,0.91993,-0.16503,...,-0.18560,0.39599,-0.11498,0.31005,0.05614,0.21443,0.20540,0.13376,0.26422,0
262,1,1.00000,0.09802,1.00000,0.25101,0.98390,0.33044,0.80365,0.53020,0.74977,...,0.75596,-0.22839,0.69187,-0.31713,0.60948,-0.40291,0.54522,-0.42815,0.44534,0

In [17]:
y = dataset.label
x = dataset.drop(columns='label')

In [18]:
x.head()

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature25,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34
104,1,0.28409,-0.31818,0.00000,0.00000,0.68182,-1.00000,0.30682,0.95833,0.64394,...,0.24242,0.17803,1.00000,-0.23864,0.06061,-0.48485,0.16288,-0.70076,0.00000,0.00000
128,1,0.00000,0.00000,-0.33672,0.85388,0.00000,0.00000,0.68869,-1.00000,0.97078,...,0.00000,0.00000,1.00000,-1.00000,0.00000,0.00000,0.04447,0.61881,0.00000,0.00000
212,1,-1.00000,-0.59677,0.00000,0.00000,-1.00000,0.64516,-0.87097,1.00000,0.00000,...,0.29839,0.23387,1.00000,0.51613,0.00000,0.00000,0.00000,0.00000,0.00000,0.00000
271,1,0.47938,-0.12371,0.42784,-0.12371,0.70103,-0.39175,0.73196,0.07216,0.26289,...,0.70619,0.19588,0.53396,-0.12447,0.15464,-0.26289,0.47423,0.04124,0.45361,-0.51546
229,1,0.73523,-0.38293,0.80151,0.10278,0.78826,0.15266,0.55580,0.05252,1.00000,...,0.94530,0.57549,0.44174,0.48200,0.12473,1.00000,0.35070,0.49721,0.30588,0.49831

In [19]:
y

104    1
128    1
212    1
271    0
229    0
      ..
318    0
202    1
299    0
338    0
262    0
Name: label, Length: 351, dtype: int64

In [20]:
# now split tha data to train and test set
from sklearn.model_selection import train_test_split

In [21]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size= 0.4 )

In [22]:
X_train

,feature1,feature3,feature4,feature5,feature6,feature7,feature8,feature9,feature10,feature11,...,feature25,feature26,feature27,feature28,feature29,feature30,feature31,feature32,feature33,feature34
85,1,0.39179,-0.06343,0.97464,0.04328,1.00000,1.00000,0.35821,0.15299,0.54478,...,0.47015,0.16418,0.49309,0.14630,0.32463,-0.02612,0.39118,0.13521,0.34411,0.12755
38,1,0.91241,0.04347,0.94191,0.02280,0.94705,0.05345,0.93582,0.01321,0.91911,...,0.75755,0.11299,0.73550,0.13282,0.66387,0.15300,0.70925,0.10754,0.65258,0.11447
197,1,1.00000,0.23058,1.00000,-0.78509,1.00000,-0.10401,1.00000,0.15414,1.00000,...,1.00000,-0.01253,0.96238,-0.04597,0.91165,0.03885,1.00000,-0.13722,0.96523,-0.11717
273,1,0.50112,-0.03596,0.61124,0.01348,0.58876,0.01573,0.58876,0.02472,0.66742,...,0.46517,0.04944,0.56588,0.00824,0.47640,-0.03596,0.54607,0.10562,0.60674,-0.08090
293,1,0.87772,-0.08152,0.83424,0.07337,0.84783,0.04076,0.77174,-0.02174,0.77174,...,0.85054,-0.18750,0.83705,-0.10211,0.85870,-0.03261,0.78533,-0.10870,0.79076,-0.00543
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
182,0,-1.00000,1.00000,1.00000,-1.00000,0.00000,0.00000,0.00000,0.00000,1.00000,...,-1.00000,1.00000,1.00000,-1.00000,-1.00000,1.00000,-1.00000,-1.00000,0.00000,0.00000
295,1,0.46785,0.11308,0.58980,0.00665,0.55432,0.06874,0.47894,-0.13969,0.52993,...,0.41463,-0.20177,0.53930,-0.11455,0.59867,-0.02882,0.53659,-0.11752,0.56319,-0.04435
87,1,0.72727,-0.05000,0.89241,0.03462,1.00000,0.72727,0.66364,-0.05909,0.48182,...,0.57273,0.32727,0.56982,0.14673,0.42273,0.08182,0.48927,0.14643,1.00000,1.00000
23,0,-1.00000,1.00000,0.00000,0.00000,0.00000,0.00000,-1.00000,1.00000,1.00000,...,-1.00000,-1.00000,1.00000,-1.00000,1.00000,1.00000,-1.00000,1.00000,0.00000,0.00000
260,1,0.50000,0.00000,0.38696,0.10435,0.49130,0.06522,0.46957,-0.03913,0.35652,...,0.47391,-0.00870,0.41789,0.06908,0.38696,0.03913,0.35217,0.14783,0.44783,0.17391

In [23]:
Y_train

85     1
38     0
197    0
273    0
293    0
      ..
182    1
295    0
87     1
23     1
260    0
Name: label, Length: 210, dtype: int64

In [98]:
# Build The Model
from tensorflow.keras.models import Sequential
from tensorflow.keras import layers
from tensorflow.keras import regularizers

In [133]:
network = Sequential()

In [134]:
network.add(layers.Dense(16, activation='relu', kernel_regularizer = regularizers.l2(0.001),  input_shape=(X_train.shape[1],)))
network.add(layers.Dense(8, activation='relu' , kernel_regularizer = regularizers.l2(0.001)))
network.add(layers.Dense(4, activation='relu' , kernel_regularizer = regularizers.l2(0.001)))
network.add(layers.Dense(1, activation='sigmoid'))

In [135]:
network.compile(optimizer='adam', loss='binary_crossentropy', metrics='accuracy')

In [136]:
network.fit(X_train, Y_train, epochs=60, batch_size=8)

Epoch 1/60
27/27 [==============================] - 0s 2ms/step - loss: 0.7321 - accuracy: 0.4286
Epoch 2/60
27/27 [==============================] - 0s 2ms/step - loss: 0.6884 - accuracy: 0.7667
Epoch 3/60
27/27 [==============================] - 0s 2ms/step - loss: 0.6581 - accuracy: 0.7952
Epoch 4/60
27/27 [==============================] - 0s 3ms/step - loss: 0.6249 - accuracy: 0.7762
Epoch 5/60
27/27 [==============================] - 0s 2ms/step - loss: 0.5801 - accuracy: 0.7905
Epoch 6/60
27/27 [==============================] - 0s 3ms/step - loss: 0.5385 - accuracy: 0.7905
Epoch 7/60
27/27 [==============================] - 0s 2ms/step - loss: 0.4950 - accuracy: 0.8429
Epoch 8/60
27/27 [==============================] - 0s 2ms/step - loss: 0.4539 - accuracy: 0.8524
Epoch 9/60
27/27 [==============================] - 0s 2ms/step - loss: 0.4136 - accuracy: 0.8952
Epoch 10/60
27/27 [==============================] - 0s 3ms/step - loss: 0.3771 - accuracy: 0.9048
Epoch 11/60
27/27 [==============================] - 0s 3ms/step - loss: 0.3427 - accuracy: 0.9143
Epoch 12/60
27/27 [==============================] - 0s 3ms/step - loss: 0.3129 - accuracy: 0.9238
Epoch 13/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2838 - accuracy: 0.9286
Epoch 14/60
27/27 [==============================] - 0s 2ms/step - loss: 0.2587 - accuracy: 0.9333
Epoch 15/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2379 - accuracy: 0.9429
Epoch 16/60
27/27 [==============================] - 0s 2ms/step - loss: 0.2214 - accuracy: 0.9619
Epoch 17/60
27/27 [==============================] - 0s 3ms/step - loss: 0.2048 - accuracy: 0.9524
Epoch 18/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1905 - accuracy: 0.9571
Epoch 19/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1803 - accuracy: 0.9667
Epoch 20/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1700 - accuracy: 0.9667
Epoch 21/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1615 - accuracy: 0.9714
Epoch 22/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1526 - accuracy: 0.9810
Epoch 23/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1483 - accuracy: 0.9714
Epoch 24/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1407 - accuracy: 0.9810
Epoch 25/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1388 - accuracy: 0.9762
Epoch 26/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1330 - accuracy: 0.9857
Epoch 27/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1291 - accuracy: 0.9762
Epoch 28/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1229 - accuracy: 0.9857
Epoch 29/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1202 - accuracy: 0.9857
Epoch 30/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1174 - accuracy: 0.9857
Epoch 31/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1139 - accuracy: 0.9857
Epoch 32/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1112 - accuracy: 0.9857
Epoch 33/60
27/27 [==============================] - 0s 3ms/step - loss: 0.1090 - accuracy: 0.9857
Epoch 34/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1065 - accuracy: 0.9857
Epoch 35/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1031 - accuracy: 0.9857
Epoch 36/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1008 - accuracy: 0.9857
Epoch 37/60
27/27 [==============================] - 0s 2ms/step - loss: 0.1004 - accuracy: 0.9905
Epoch 38/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0972 - accuracy: 0.9857
Epoch 39/60
27/27 [==============================] - 0s 3ms/step - loss: 0.0962 - accuracy: 0.9905
Epoch 40/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0942 - accuracy: 0.9857
Epoch 41/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0945 - accuracy: 0.9857
Epoch 42/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0914 - accuracy: 0.9905
Epoch 43/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0879 - accuracy: 0.9905
Epoch 44/60
27/27 [==============================] - 0s 3ms/step - loss: 0.0876 - accuracy: 0.9905
Epoch 45/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0853 - accuracy: 0.9905
Epoch 46/60
27/27 [==============================] - 0s 3ms/step - loss: 0.0838 - accuracy: 0.9905
Epoch 47/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0822 - accuracy: 0.9905
Epoch 48/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0808 - accuracy: 0.9905
Epoch 49/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0809 - accuracy: 0.9905
Epoch 50/60
27/27 [==============================] - 0s 3ms/step - loss: 0.0790 - accuracy: 0.9905
Epoch 51/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0760 - accuracy: 0.9952
Epoch 52/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0752 - accuracy: 0.9952
Epoch 53/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0745 - accuracy: 0.9952
Epoch 54/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0727 - accuracy: 0.9952
Epoch 55/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0716 - accuracy: 0.9952
Epoch 56/60
27/27 [==============================] - ETA: 0s - loss: 0.0701 - accuracy: 0.99 - 0s 3ms/step - loss: 0.0717 - accuracy: 0.9952
Epoch 57/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0735 - accuracy: 0.9952
Epoch 58/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0693 - accuracy: 0.9952
Epoch 59/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0678 - accuracy: 0.9952
Epoch 60/60
27/27 [==============================] - 0s 2ms/step - loss: 0.0655 - accuracy: 0.9952

In [137]:
prediction = network.predict(X_test)

In [138]:
network.evaluate(X_test, Y_test)

5/5 [==============================] - 0s 2ms/step - loss: 0.2613 - accuracy: 0.9220

[0.26133233308792114, 0.9219858050346375]

In [139]:
prediction.shape

(141, 1)

In [140]:
prediction=prediction.reshape(141)

In [141]:
output = pd.DataFrame({'Actual': Y_test})

In [142]:
output['prediction'] = prediction

In [143]:
output.reset_index(inplace=True)

In [144]:
output

     index  Actual  prediction
0      220       1    1.000000
1      213       0    0.025307
2      244       1    0.779243
3      109       0    0.003928
4      144       1    0.011084
..     ...     ...         ...
136     96       0    0.003758
137    155       0    0.003243
138    145       0    0.077721
139    200       1    0.972264
140    276       0    0.011699

[141 rows x 3 columns]